### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by Nicholas-Baron** [JamesGaier/Minesweeper#10]
Chrome gives an error in the console when I try to run the website from terminal.
```
Access to script at 'file:///.../public/scripts/output/index.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
```
The issue is that the files which are not the index.html must come from a http(s) URL to load.

This speeds up the issue of deployment platform.

**Comment by JamesGaier** [comment]
You should not be trying to run index.html from the terminal. https://stackoverflow.com/questions/55252192/from-origin-null-has-been-blocked-by-cors-policy-cross-origin-requests?noredirect=1&lq=1
edit nvm
